import { test, expect } from '@playwright/test';

test('has title', async ({ page }) => {
  await page.goto(process.env.BASE_URL || 'https://www.amazon.com');
  await page.getByRole('link', { name: 'Sign in', exact: true }).click();
  await page.getByRole('link', { name: 'Create your Amazon account' }).click();
  await page.getByRole('textbox', { name: 'Mobile number or email' }).fill('mdlukman+uk2@amazon.com');
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill('kindleda');
  await page.getByRole('textbox', { name: 'Re-enter password' }).fill('kindleda');
  await page.getByRole('button', { name: 'Continue Verify mobile number' }).click();
  await page.getByRole('textbox', { name: 'Enter security code' }).fill('950366');
  await page.getByRole('button', { name: 'Verify OTP Button' }).click();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.getByRole('button', { name: 'Submit' }).first().click();
  await page.getByRole('button', { name: 'Expand Account and Lists' }).click();
  await page.getByRole('link', { name: 'Content Library' }).click();
  await page.getByRole('link', { name: 'Preferences' }).click();
  await page.getByLabel('Primary').getByRole('link', { name: 'Books' }).click();
  await page.getByRole('link', { name: 'Your Account', exact: true }).click();
  await page.getByRole('link', { name: 'Content and devices', exact: true }).click();
  await page.getByRole('link', { name: 'Preferences' }).click();
  await page.getByText('Change your country/region').click();
  await page.getByRole('button', { name: 'Change', exact: true }).click();
  await page.getByRole('textbox', { name: 'Address Line 1: (or company' }).click();
  await page.getByRole('textbox', { name: 'Address Line 1: (or company' }).fill('Street 1');
  await page.getByRole('textbox', { name: 'Town/City:' }).click();
  await page.getByRole('textbox', { name: 'Town/City:' }).fill('London');
  await page.getByRole('textbox', { name: 'County:' }).click();
  await page.getByRole('textbox', { name: 'County:' }).fill('United Kingdom');
  await page.getByRole('textbox', { name: 'Postcode:' }).click();
  await page.getByRole('textbox', { name: 'Postcode:' }).fill('W112BQ');
  await page.getByRole('textbox', { name: 'Phone number:' }).click();
  await page.getByRole('textbox', { name: 'Phone number:' }).fill('9876543210');
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('link', { name: 'Your Payments' }).click();
  await page.locator('input[name="ppw-widgetEvent\\:ChangeAddressPreferredPaymentMethodEvent\\:\\{\\"addressId\\"\\:\\"CSCRJACBG3BQI65RCX7UG13E91093IPP2BAB2PPI39019EDPXTQ2EIA2OXRA55DV\\"\\}"]').click();
  await page.getByRole('link', { name: 'Add a credit or debit card' }).click();
  await page.locator('iframe[name="ApxSecureIframe-pp-AldJoC-46"]').contentFrame().getByRole('textbox', { name: 'Name on card' }).click();
  await page.locator('iframe[name="ApxSecureIframe-pp-AldJoC-46"]').contentFrame().getByRole('textbox', { name: 'Name on card' }).fill('Mohammed Lukmanudhin');
  await page.locator('iframe[name="ApxSecureIframe-pp-AldJoC-46"]').contentFrame().getByRole('textbox', { name: 'Card number' }).click();
  await page.locator('iframe[name="ApxSecureIframe-pp-AldJoC-46"]').contentFrame().getByRole('textbox', { name: 'Card number' }).fill('4444 3333 2222 1111');
  await page.locator('iframe[name="ApxSecureIframe-pp-AldJoC-46"]').contentFrame().locator('span').filter({ hasText: '2025' }).nth(3).click();
  await page.locator('iframe[name="ApxSecureIframe-pp-AldJoC-46"]').contentFrame().getByLabel('2034').getByText('2034').click();
  await page.locator('iframe[name="ApxSecureIframe-pp-AldJoC-46"]').contentFrame().getByRole('button', { name: 'Add your card' }).click();
  await page.locator('iframe[name="ApxSecureIframe-pp-AldJoC-46"]').contentFrame().getByRole('button', { name: 'Use this address' }).click();
  await page.locator('input[name="ppw-widgetEvent\\:PreferencePaymentOptionSelectionEvent"]').click();
});